// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjDEa2IaSVCIUfZoui1LBmtJC8suAoX5E',
    appId: '1:1025047434286:web:b814900d8f55dfc336fbbf',
    messagingSenderId: '1025047434286',
    projectId: 'flutter-chat-app-a63d8',
    authDomain: 'flutter-chat-app-a63d8.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a63d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd41QgptRbvvAYAskmf_alYU7Qy48VRbc',
    appId: '1:1025047434286:android:30e440b4841e3a1336fbbf',
    messagingSenderId: '1025047434286',
    projectId: 'flutter-chat-app-a63d8',
    storageBucket: 'flutter-chat-app-a63d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiDSXr_UPXOlPRzZGP1CWhStBCCBDGqaw',
    appId: '1:1025047434286:ios:8bc887430e30667c36fbbf',
    messagingSenderId: '1025047434286',
    projectId: 'flutter-chat-app-a63d8',
    storageBucket: 'flutter-chat-app-a63d8.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}
